jobs: 4
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
        - pymdownx.superfences
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:    
      # Ignore URL in hyperlinks [title](url)
      - open: '\]\('
        close: '\)'
  - pyspelling.filters.html:
      comments: false
      ignores:
      - ':matches(code, pre)'
      - code
      - pre
  sources:
  - '**/*.md'
  - '**/*.mdx'
  default_encoding: utf-8