jobs: 4
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.url:
  # - pyspelling.filters.markdown:
  #     markdown_extensions:
  #       - pymdownx.superfences
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore multiline content between fences
      - open: '(?s)^(?P<open> *```)[a-z]*$'
        close: '^(?P=open)$'
      # Ignore text between inline back ticks
      - open: '(?P<open>`+)'
        close: '(?P=open)'
      # Ignore URL in hyperlinks [title](url)
      - open: '\]\('
        close: '\)'
      # Bolded words are usually terms
      - open: '[*]+'
        close: '[*]+'
      # Inside HTML tags
      #- open: '(?s)(?P<open>[<])'
      #  close: '[>]'
      # Ignore possessive endings
      - open: '(?<=\w)''s(?!\w)'
        close: '\b'
  - pyspelling.filters.html:
      comments: false
      ignores:
      - ':matches(code, pre)'
      - code
      - pre
  sources:
  - '**/*.md'
  - '**/*.mdx'
  default_encoding: utf-8